http:
  services:
    websockify-proxy:
      loadBalancer:
        servers:
          - url: "http://backend:6080"
    frontend:
      loadBalancer:
        servers:
          - url: "http://frontend:80"
